INSERT INTO TRECHO_RODOVIA
(QUILOMETRO_INICIAL,
 QUILOMETRO_FINAL,
 NIVEL_VEGETACAO_CM,
 TIPO_CLIMA)
VALUES
    (0, 10, 8, 'seco');


INSERT INTO TRECHO_RODOVIA
(QUILOMETRO_INICIAL,
 QUILOMETRO_FINAL,
 NIVEL_VEGETACAO_CM,
 TIPO_CLIMA)
VALUES
    (15, 20, 15, 'umido');


INSERT INTO TRECHO_RODOVIA
(QUILOMETRO_INICIAL,
 QUILOMETRO_FINAL,
 NIVEL_VEGETACAO_CM,
 TIPO_CLIMA)
VALUES
    (25, 30, 30, 'umido');


INSERT INTO TRECHO_RODOVIA
(QUILOMETRO_INICIAL,
 QUILOMETRO_FINAL,
 NIVEL_VEGETACAO_CM,
 TIPO_CLIMA)
VALUES
    (35, 40, 5, 'seco');


INSERT INTO TRECHO_RODOVIA
(QUILOMETRO_INICIAL,
 QUILOMETRO_FINAL,
 NIVEL_VEGETACAO_CM,
 TIPO_CLIMA)
VALUES
    (45, 50, 22, 'seco');


COMMIT;